<form action="AgregarCriadero" method="POST">
        <label for="">Nombre Criadero</label>
        <input type="text" name="nombre" required><br>

        <label for="">Direccion</label>
        <input type="text" name="direccion" required><br>

        <label for="">Localidad</label>
        <input type="text" name="localidad" required><br>

        <label for="">Raza</label>
        <input type="text" name="raza" required><br>

        <label for="imagen">URL Imagen</label>
        <input type="text" name="imagen" required><br>

        <input type="submit" value="Agregar">
</form>