<main>
    <div class="container2">

            <ul class="list-group">
            
                <li class="list-group-item" >
                    <img src="<?=$perros->Imagen?>" alt="" srcset="">
                    <p>Nombre: <?=$perros->nombre?></p>
                    <p>Identificador Perro: <?=$perros->id_perro?></p>
                    <p>Identificador Criadero: "<?=$perros->id_criadero?>"</p>
                    <p>Sexo: <?=$perros->sexo?></p>
                    <p>Fecha de nacimiento: <?=$perros->nacimiento?></p>
                    <p>Nombre del padre: <?=$perros->padre?></p>
                    <p>Nombre de la madre: <?=$perros->madre?></p>

                    
                </li>
            
        </ul>
    
    </div>
</main>