<main>
<?php  foreach ($criaderos as $criadero): ?>
    <ul class="list-group">
        
            <li class="list-group-item" >
                <img src="<?=$criadero->Imagen?>" alt="" srcset="">
                <a href="http://localhost/TPE2/FormularioEditarCategoria/<?=$criadero->id_criadero?>"><p>Editar "<?=$criadero->Nombre?>"</p></a>
                
            </li>
        
    </ul>
    <?php endforeach ?>
</main>


