<!-- Header-->
<?php require_once './templates/head.phtml' ?>

<body>
    <header>
        <h1 class="titulos">Criaderos de perros</h1>
    </header>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid shadow">
            <ul class="container3">
                <li class="navbar-text">
                    <a  href=""> Home </a>
                </li>
                
                <?php if (isset($_SESSION["USER_ID"]) && !empty($_SESSION["USER_ID"])): ?>
                <li class="navbar-text">
                    <a href="logout">Logout</a>
                </li>
                <?php else: ?>
                <li class="navbar-text">
                    <a href="showLogin" >Login</a>
                </li>
                <?php endif ?>
            </ul>
        </div>
    </nav>


