<!-- Header-->

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criaderos de perros</title>
    <link rel="stylesheet" href="./CSS/style.css">
</head>
<body>
    <header>
    <h1 class="titulos">Criaderos de perros de la provincia de Bueno Aires</h1>
    <nav>
        <div >
            <ul id="nav">
                <a class="li" href="http://localhost/TPE2/home"><li class="titulos">Home</li></a>
                <a class="li" href="http://localhost/TPE2/usuario"><li class="titulos">Usuario</li></a>
                
            </ul>
        </div>
    </nav>
    </header>

