<main>
    <ul class="list-group">
        <div class="funciones" >
            <!-- Imagen a la izquierda -->
            <div>
                
                    <li class="list-group-item" type="button">Administrar Criaderos</li>
                
                <img src="https://mascotafiel.com/wp-content/uploads/2015/10/criaderos-de-perros_opt-compressor-1.jpg" alt="" >
            </div>
            
            <!-- Botones a la derecha -->
            <div class="listado" >
                <a href="http://localhost/TPE2/listadoCategorias">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Listar</li>
                </a>
                <a href="http://localhost/TPE2/AgregarCategoria">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Agregar</li>
                </a>
                <a href="http://localhost/TPE2/EditarCategoria">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Editar</li>
                </a>
                <a href="http://localhost/TPE2/EliminarCategoria">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Eliminar</li>
                </a>
            </div>
        </div>

        <!-- Otra sección (opcionalmente puedes repetir este bloque para otra categoría) -->
        <div class="funciones" >
            <!-- Imagen a la izquierda -->
            <div>
                
                    <li class="list-group-item" type="button">Administrar Perros</li>
                
                <img src="https://i.anunciosgratis.com.ar/i-a/0OFp-16.jpg" alt="" >
            </div>
            
            <!-- Botones a la derecha -->
            <div class="listado" >
                <a href="http://localhost/TPE2/listadoItems">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Listar</li>
                </a>
                <a href="http://localhost/TPE2/AgregarPerro">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Agregar</li>
                </a>
                <a href="http://localhost/TPE2/EditarPerro">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Editar</li>
                </a>
                <a href="http://localhost/TPE2/EliminarPerro">
                    <li class="list-group-item btn btn-success btn-sm ml-auto" type="button">Eliminar</li>
                </a>
            </div>
        </div>
    </ul>
</main>